trigger:
  branches:
    include:
      - main

stages:
- stage: Terraform
  displayName: 'Provision Infrastructure'
  jobs:
  - job: Terraform_Apply
    displayName: 'Terraform Apply'
    pool:
      name: 'linux-hosted-pool'

    steps:
    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: 'id_rsa.pub'

    - script: |
        echo "Copying SSH public key into Terraform module"

        # Ensure SSH folder exists in agent
        mkdir -p ~/.ssh
        cp $(download_ssh_key.secureFilePath) ~/.ssh/id_rsa.pub

        # Ensure the Terraform compute module folder exists in project
        mkdir -p infra-epicbook/modules/compute

        # Copy the SSH public key into compute module
        cp $(download_ssh_key.secureFilePath) infra-epicbook/modules/compute/id_rsa.pub

        # Confirm the file is in place
        echo "Listing contents of infra-epicbook/modules/compute/"
        ls -al infra-epicbook/modules/compute/
      displayName: 'Extract SSH Public Key for Terraform'



    # ✅ Install Azure CLI (good since you're using AzureCLI@2)
    - task: Bash@3
      displayName: 'Install Azure CLI'
      inputs:
        targetType: 'inline'
        script: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az --version

  

    # ✅ Run Terraform properly (no double 'cd')
    - task: AzureCLI@2
      displayName: 'Terraform Init/Plan/Apply'
      inputs:
        azureSubscription: 'epicbook-service'
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)
        inlineScript: |
          set -e
          echo "##[group]Terraform Init/Plan/Apply"

          terraform init -input=false
          terraform plan -input=false -var-file=envs/dev.tfvars
          terraform apply -input=false -auto-approve -var-file=envs/dev.tfvars

          echo "##[endgroup]"

